assessment first attempt
learn-academy-2023-charlie/week-5-assessment-henrike32 pull request #1
Opened 2023-05-19 23:19 UTC by henrike32

# Submitting Week 5 Assessment

### ✅ Completed Files

Mark the following as confirmation that the files in this repository are complete.

- [ ] JavaScript Coding Challenges
- [ ] Ruby Coding Challenges
- [ ] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:

2023-05-22 19:43 UTC, chrisyhlee requested changes
Waiting for code challenge 3

2023-05-22 19:43 UTC, chrisyhlee commented on code-challenges.test.js
> +// input -> returns a string with a coded message which converts "a" to 4, "e" to 3, "i" to 1, and "o" to 0.
input and output are reversed

2023-05-22 19:43 UTC, chrisyhlee commented on code-challenges.test.js
> +// Method 1:
Based on your pseudo code, it seems like you don't fully understand what is happening with this solution.
- make an object with key value pairs representing letters to match and their replacement
- use .replace to iterate through string
- use regex with the letters to look for, using the g flag to find all occurrences, not just the first
- callback function will find each match and replace the matched letter with the value in the object

2023-05-22 19:43 UTC, chrisyhlee commented on code-challenges.test.js
> +        if (arr[i].includes(letter)){
Great thought process, but what about the capital A in 'Apricot'? This currently won't push that word into the newArray.

2023-05-22 19:43 UTC, chrisyhlee commented on ruby-challenges.rb
> +# result1 = beverages_array.select! { |string| string.include?(filter_letter_o) }
Keep in mind that the prompt is asking you to create a method, not a variable

2023-05-22 19:43 UTC, chrisyhlee commented on ruby-challenges.rb
> +        # had to find a way to increase the initial speed and maintain the value, didn't knew if I could use 'Integer' as a incremental value, tried this out and it worked! Happy to actually do some
Big win!! Nice work!

2023-05-22 19:43 UTC, chrisyhlee commented on ruby-challenges.rb
> +        #     "Negative speed doesn't exist"
Remember you still want to set current_speed to something. The lowest it can be is 0

2023-05-24 17:05 UTC, merged

2023-05-25 23:41 UTC, chrisyhlee reviewed
I see you added your classmates' approaches to your own. This is great, but only if you are taking the time to understand each approach and learning from them. If you don't, you are not gaining anything out of it, which is only hurting yourself in the end. I am available to reach out to at any time, and I highly suggest you go to your mentor with these approaches and any concepts you don't understand! This displays Novice level currently. I believe in you Henri, keep working hard!

2023-05-26 05:25 UTC, henrike32 commented
I've been paying attention to their approach on the coding part, most of the codes I've added to the assessment refactor the owner explained during the assessment review. Later on I will make a single file with all of these ways to do certain functions , so I can always refer when needed.